"""Added Notification table

Revision ID: 02b6c7a03821
Revises: fe97f3527a48
Create Date: 2023-12-19 17:47:24.732122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b6c7a03821'
down_revision: Union[str, None] = 'fe97f3527a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Notification',
    sa.Column('N_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NB_group', sa.String(length=100), nullable=False),
    sa.Column('NF_name', sa.String(length=100), nullable=False),
    sa.Column('N_packets', sa.Integer(), nullable=True),
    sa.Column('N_Adress', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('N_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Notification')
    # ### end Alembic commands ###
