"""Added Donor table

Revision ID: 32e1870de6a1
Revises: faf0ac8dff0a
Create Date: 2023-12-19 09:03:14.281094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e1870de6a1'
down_revision: Union[str, None] = 'faf0ac8dff0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Donor',
    sa.Column('D_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Dname', sa.String(length=100), nullable=True),
    sa.Column('Sex', sa.String(length=10), nullable=True),
    sa.Column('Age', sa.String(length=10), nullable=True),
    sa.Column('Weight', sa.Integer(), nullable=True),
    sa.Column('Address', sa.String(length=100), nullable=True),
    sa.Column('Disease', sa.String(length=100), nullable=True),
    sa.Column('Demail', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('D_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Donor')
    # ### end Alembic commands ###
