"""Added BloodBank table

Revision ID: 3bde2960873e
Revises: 32e1870de6a1
Create Date: 2023-12-19 09:08:03.671057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bde2960873e'
down_revision: Union[str, None] = '32e1870de6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BloodBank',
    sa.Column('B_group', sa.String(length=50), autoincrement=True, nullable=False),
    sa.Column('Total_packets', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('B_group')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BloodBank')
    # ### end Alembic commands ###
