"""Added BloodBank table

Revision ID: 7708ec448833
Revises: ff6d2d45a8c4
Create Date: 2023-12-19 17:43:35.232106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7708ec448833'
down_revision: Union[str, None] = 'ff6d2d45a8c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BloodBank',
    sa.Column('B_group', sa.String(length=100), nullable=False),
    sa.Column('Total_packets', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('B_group')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BloodBank')
    # ### end Alembic commands ###
