"""Added Reception table

Revision ID: faf0ac8dff0a
Revises: 4eacb4180971
Create Date: 2023-12-18 20:31:31.155462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf0ac8dff0a'
down_revision: Union[str, None] = '4eacb4180971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Reception',
    sa.Column('E_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('E_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reception')
    # ### end Alembic commands ###
