"""Added Reception and Donor table

Revision ID: ff6d2d45a8c4
Revises: 1f7b697e6b93
Create Date: 2023-12-19 17:41:45.614598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff6d2d45a8c4'
down_revision: Union[str, None] = '1f7b697e6b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
